import { ENV } from "src/config/app";

export const API_URLS = {
  auth: {
    register: "/api/user/register",
    verify: (id, token) => `/api/user/verify/${id}/${token}`,
    login: "/api/user/login",
    forgotPassword: "/api/user/reset-password",
    updatePassword: ({ userId, token }) => `/api/user/update-password/${userId}/${token}`,
  },
  user: {
    me: "/api/user/me",
    update: "/api/user/update",
    addOrRemoveFavorite: "/api/user/addOrRemoveFavourite",
    getUserFavorites: "/api/user/getUserFavouriteCars",
    getAll: "/api/user/getAll",
    delete: "/api/user/delete",
  },
  cars: {
    getAll: "/api/car/getAll",
    getById: "/api/car/getById",
    getByRegNo: "/api/car/getByRegNo",
    carsList: "/api/car/carsList",
    carsBodyList: "/api/car/carsBodyList",
    getCarModelsByCar: "/api/car/getCarModelsByCar",
    getCarModelsByYear: "/api/car/getCarModelsByYear",
    filterByMakeAndModel: "/api/car/filterByMakeAndModel",
    sendEmailToCarOwner: "/api/car/sendEmailToCarOwner",
    uploadCarImages: "/api/car/uploadCarImages",
    getMyCars: "/api/car/my-cars",
    add: "/api/car/add",
    update: "/api/car/update",
    delete: "/api/car/delete",
  },
  blog: {
    getAll: "/api/blog/getAll",
    add: "/api/blog/add",
    update: "/api/blog/update",
    delete: "/api/blog/delete",
  },
  video: {
    getAll: "/api/video/getAll",
    getById: "/api/video/getById",
    getByCategory: "/api/video/getByCategory",
    getByOwner: "/api/video/getByOwner",
    add: "/api/video/add",
    update: "/api/video/update",
    delete: "/api/video/delete",
  },
  ads: {
    getAll: "/api/ads/getAll",
    add: "/api/ads/add",
    update: "/api/ads/update",
    delete: "/api/ads/delete",
  },
  admin: {
    login: "/api/admin/login",
    register: "/api/admin/register",
    update: "/api/admin/update",
    get: "/api/admin/get",
  },
};
